// The first name each U.S. president is commonly known by (e.g. "Bill" not
// "William" for Clinton, "Jimmy" not "James" for Carter), deduped since many
// presidents share a first name.
export const presidentialNames: Set<string> = new Set([
  "george",
  "john",
  "thomas",
  "james",
  "andrew",
  "martin",
  "william",
  "zachary",
  "millard",
  "franklin",
  "abraham",
  "ulysses",
  "rutherford",
  "chester",
  "grover",
  "benjamin",
  "theodore",
  "woodrow",
  "warren",
  "calvin",
  "herbert",
  "harry",
  "dwight",
  "lyndon",
  "richard",
  "gerald",
  "jimmy",
  "ronald",
  "bill",
  "barack",
  "donald",
  "joe",
]);
