name: UBP
channels:
  - conda-forge
dependencies:
  - python=3.14
  - magic-wormhole~=0.24.0
  - just~=1.51.0
  - cookiecutter~=2.7.1
  - nodejs~=26.5.1
  - pytest~=9.1.1
  - httpx~=4.12.1
  - uv~=0.12.17
  - ruff~=0.16.7
